### ISSUE TITLE
lookAt()方法只生效一帧就失效了

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#10]
### 问题描述

engine.camera.lookAt()函数不能设置target

### 问题或报错截图

无报错，很奇怪

### 运行环境:

- 系统: windows@10
- 浏览器： chrome@131
- 脚手架： vite@2.9.15
- node：14.20.0
- 其他附加

### 附加代码上下文或者可调试环境

毕竟处理问题的人并不是提问人员，除了报错之外，很多时候是使用与需求冲突，请提供出错时代码的上文，还有与此功能关联的代码模块。

如果功能偏多，请将功能简化后形成可下载调试的开源仓库或者在线调试环境。

然后提供相关的开源仓库连接或者在线调试连接。

### 操作或者编码逻辑

1. 先使用了什么
2. 然后发现影响了什么
3. 看见了错误

### 预期行为

应该看向我设置的值

### 解决问题的回报选择

- [x] 提供修复 pr 或者完善项目（文档完善，代码优化，示例优化等等）。
- [ ] 一定的赞助资金。

> 为了避免形成白嫖习惯和依赖性习惯，对于非 bug，或者非新增，非特色等提问需要选择回报模式，比如一些信息可以从文档获取，或者是自己的技术水平和理解水平导致的问题，能够提供一定的警醒作用。具体详情请进入：QQ 群：586362945 详谈。

**Comment by Shiotsukikaedesari** [comment]
给出engine的设置和没有实现功能的代码上下文。

目前来看是技术和理解问题。先选择解决问题的回报模式。

**Comment by sheerhr** [comment]
// 物体选择
engine.addEventListener("selected", (event) => {
  // engine.camera.lookAt(event.objects[0].position)
  const endPoint = event.objects[0].position
  //计算起始点与终点之间的向量
  const knowVector = endPoint.clone().sub(startPoint);
  // 计算连接向量的终点
  const targetVector = engine.camera.position.clone().add(knowVector);
  engine.camera.position.copy(targetVector)

  engine.camera.lookAt(event.objects[0].position)

  startPoint.copy(targetVector)
  就是点击mesh的时候想让相机看向mesh

**Comment by Shiotsukikaedesari** [comment]
如果engine有使用orbitControls，engine的相机会被controls托管，会始终看向controls的target，所以应该修改controls的target而不是相机。

参照文档：https://threejs.org/docs/index.html?q=or#examples/zh/controls/OrbitControls

提供修复 pr 或者完善项目方式去到issue中选取相关**任务**进行就行。

**Comment by sheerhr** [comment]
ok
