### ISSUE TITLE
项目装包报错

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#13]
### 问题描述

```bash
node版本:16.12.0
pnpm版本:6.11.5
```

### 问题或报错截图

request to https://registry.npmjs.org/@cypress/code-coverage/-/code-coverage-3.10.0.tgz failed, reason: connect ECONNREFUSED 127.0.0.1:21882

### 运行环境

```bash
系统: windows@10
浏览器： chrome@131
脚手架： vite@2.9.15
node: 16.12.0
```

### 解决问题的回报选择

提供修复 pr 或者完善项目（文档完善，代码优化，示例优化等等）

**Comment by Shiotsukikaedesari** [comment]
pnpm会读取.npmrc文件，目前.npmrc文件里面配了默认代理进行http的加速，如果没有类似服务注释掉就行，后面会忽略.npmrc的改动
