### ISSUE TITLE
pathDrawingPlugin如何才能设置z坐标让线段在别的平面上也可以绘制出来，现在只能在xoy平面上进行绘制

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#14]
### 问题描述

```bash
希望可以路径绘制插件可以提供绘制z坐标的能力
```

### 问题或报错截图

无

### 运行环境

```bash
系统: windows@10
浏览器： chrome@131
脚手架： vite@2.9.15
node: 14.20.0
```

### 解决问题的回报选择

提供修复 pr 或者完善项目（文档完善，代码优化，示例优化等等）

**Comment by Shiotsukikaedesari** [comment]
这应该是一个feature，希望能使用feature模板进行描述。

**Comment by Shiotsukikaedesari** [comment]
目前的path只是2Dpath，如果你所希望的功能是绘制3Dpath，这应该是一个feature，希望能用feature的issue进行描述。
