### ISSUE TITLE
path配置化的三维路径绘制支持

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#15]
### 功能描述

希望能提供一个能在任意平面进行路径绘制的api

### 使用场景

场景漫游功能，需要绘制漫游路径再进行相机动画制作

**Comment by Shiotsukikaedesari** [comment]
3D路径需要先新增path3 配置模块，不过貌似pathDrawingPlugin是支持任意平面的，通过setDrawPlane，setRelativeObject或者setDrawPlaneByFace等api设置，不过如果编辑path配置只能够支持二维路径。

**Comment by sheerhr** [comment]
> 3D路径需要先新增path3 配置模块，不过貌似pathDrawingPlugin是支持任意平面的，通过setDrawPlane，setRelativeObject或者setDrawPlaneByFace等api设置，不过如果编辑path配置只能够支持二维路径。

是可以设置平面，但最后绘制出来的线段只能在xoy平面上，应该是pathprocessor里边只有lineCurve，没有lineCurve3的问题，可以采用不用插件，自定义的方式去绘制吗？

**Comment by Shiotsukikaedesari** [comment]
可以只用pathDrawingPlugin插件，但是不用path module，不过需要自己实现一套曲线转线物体的渲染逻辑。

**Comment by sheerhr** [comment]
> 可以只用pathDrawingPlugin插件，但是不用path module，不过需要自己实现一套曲线转线物体的渲染逻辑。

就是我要定义一个CONFIGTYPE.3DPATH，然后去实现这个渲染逻辑是么

**Comment by Shiotsukikaedesari** [comment]
如果你想沿用配置化层的特性，可以通过新增path3配置化内容实现，这部分内容我会发布相关详细的任务issue，你可以选择新增到框架内，或者选择本地化，然后做为module的拓展内容，如果不想沿用配置化层的特性，那就需要自己实现一套画线逻辑，毕竟pathDrawingPlugin只提供绘制时的取点能力，其他的不提供。

**Comment by sheerhr** [comment]
> > 曲线转线物体的渲染逻辑。
> 
> 就是我要定义一个CONFIGTYPE.3DPATH，然后去实现这个渲染逻辑是么

好的好的，我先本地化吧，俺这之前还没有提交过pr，之后有时间提一下，到时候望老哥指点一二

**Comment by Shiotsukikaedesari** [comment]
对应的任务issue：https://github.com/vis-three/vis-three/issues/16
