### ISSUE TITLE
包结构优化

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#17]
### 功能描述

最近看了一下tresjs的文档，发现这个库把插件的管理都放在Cientos这个包下边，在读vis-three的文档时发现插件都是独个分散的，看起来很难受，这个可以优化一下吗。以下是这个库的链接https://docs.tresjs.org/guide/，https://cientos.tresjs.org/。(ps：最近在学习图形学基础和threejs，感觉暂时没有能力对库做改进，望您见谅)

**Comment by Shiotsukikaedesari** [comment]
从你的描述上和示例来看，你的核心需求是希望有一个统一的包，管理所有插件，这样子不需要每个插件都重复进行npm安装是吧？

**Comment by sheerhr** [comment]
嗯，是的

**Comment by Shiotsukikaedesari** [comment]
这个可以通过提供一个@vis-three/library-plugin的包进行，集成模式和@vis-three/library-module一样。

插件进行拆分打包主要是当初考虑到代码量和npm下载还有开发模式的一些问题，比如：
1、在功能拓展和发展的推进下会有非常多的插件，这样在一个插件包内未来进行npm下载的体量可能会很大。
2、需要为不同场景下的开发需求考虑，比如我的场景需求很简单，只用2个插件就能够完成，我还要通过下载全量的插件包会产生很多冗余。
3、对于复杂业务和特定专业的业务需求，其实更多的时候是项目内自己管理自己的一套插件体系，因为官方提供的插件很难满足很特定复杂的业务需求，所以在那个时候，也不用下载很多的插件。

考虑到以上的一些预设，所以当初的插件设计才是单独进行。不过目前也有相应的解决方案。

**Comment by sheerhr** [comment]
TreeShaking应该可以解决这个冗余的问题吧,这方面我没有深入研究过。。

**Comment by Shiotsukikaedesari** [comment]
TreeShaking只能够在有预编译条件下的项目功能才行，对于cdn或者unpkg、iife、es runtime等项目就会有比较大的冗余和生产耗损。

**Comment by Shiotsukikaedesari** [comment]
任务链接：https://github.com/vis-three/vis-three/issues/18

**Comment by Shiotsukikaedesari** [comment]
0.7版本增加了@vis-three/library-plugin和@vis-three/library-strategy两个库。
