### ISSUE TITLE
能否提供一份英文文档以供threejs社区来讨论一下这个框架

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#19]
### 功能描述

希望能提供一份英文文档

### 使用场景

供全世界的threejs社区成员来讨论一下这个框架的价值和意义所在

**Comment by Shiotsukikaedesari** [comment]
我也希望，不过最主要的问题是我一个人没什么时间，还有就是我本身的英文底子不够，不好做翻译。这个feature会发布为task，看看有没有有缘人提供。

**Comment by Shiotsukikaedesari** [comment]
对应任务： https://github.com/vis-three/vis-three/issues/20

**Comment by Shiotsukikaedesari** [comment]
首先感谢 @xiechangle ，因为文档地址：https://vis-three.github.io/docs/en/
