### ISSUE TITLE
怎么通过脚本动画设置一个不在原点的模型进行自转？

### ISSUE THREAD

**Issue by baoxukang123** [vis-three/vis-three#21]
### 问题描述

```bash
1. 我做了什么...
2. 希望实现什么 ...
3. 但是实际上是什么 ...
4. 我认为问题可能出现在哪里...
```

### 问题或报错截图

![20240115-182044](https://github.com/vis-three/vis-three/assets/143592190/238d2d1b-3e1a-4de2-9fae-bad63fe0df23)

### 运行环境

```bash
系统: windows@10
浏览器： chrome@131
脚手架： vite@2.9.15
node: 14.20.0
```

### 解决问题的回报选择

提供修复 pr 或者完善项目（文档完善，代码优化，示例优化等等）

**Comment by Shiotsukikaedesari** [comment]
有两种方案：
1、新增绕轴旋转的脚本动画，可以参考@vis-three/library-animate-script库的脚本添加：https://github.com/vis-three/vis-three/tree/main/packages/library/aniScript，添加之后自行注册调用。
2、使用空对象或组，将需要的对象添加入空对象和组中，空对象和组在原点不动，调节对象的位置，然后对空对象或组施加旋转动画。

**Comment by baoxukang123** [comment]
const wheel1Geometry = generateConfig(
            CONFIGTYPE.LOADGEOMETRY,
            Object.assign(Object.values(resourceConfig["/model/wheel/wheel1.obj"].geometry)[0], {
                scale: {
                    x: 0.5,
                    y: 0.5,
                    z: 0.5,
                },
            })
        );

        const wheel1Material = generateConfig(CONFIGTYPE.MESHSTANDARDMATERIAL, {
            color: "rgb(25,24,24)",
            metalness: 1,
            roughness: 0,
            opacity: 0.8,
        });

        const wheel1Mesh = generateConfig(CONFIGTYPE.MESH, {
            geometry: wheel1Geometry.vid,
            material: wheel1Material.vid,
        });


        const group = generateConfig(CONFIGTYPE.GROUP, {
            position: {
                x: 0,
                y: 0,
                z: 0,
            },
          children: [wheel1Mesh.vid],
        });

        generateConfig(CONFIGTYPE.SCRIPTANIMATION, {
            target: group.vid,
            attribute: ".rotation.z",
            script: AniScriptLibrary.generateConfig("linearTime", {
                multiply: 1,
            }),
        });
这里拿到一个模型几何体并设置它的材质，合成一个网格，创建一个空组并设在原点，将网格放入空组中，并对空组实施旋转动画，请问怎么调整对象的位置

**Comment by baoxukang123** [comment]
请问我打印出来的Mesh，未查看到quaternion属性，是没有存在吗？

**Comment by Shiotsukikaedesari** [comment]
查看文档，网格物体配置继承实体物体配置再继承物体配置。通过设置物体配置属性进行。

网格物体：https://vis-three.github.io/docs/library/module/mesh/readme.html
实体物体：https://vis-three.github.io/docs/library/module/solidObject/readme.html#%E6%8F%90%E4%BE%9B%E9%85%8D%E7%BD%AE
物体配置：https://vis-three.github.io/docs/library/module/object/readme.html#%E6%8F%90%E4%BE%9B%E9%85%8D%E7%BD%AE

**Comment by Shiotsukikaedesari** [comment]
> 请问我打印出来的Mesh，未查看到quaternion属性，是没有存在吗？

给出打印的写法或者代码

**Comment by baoxukang123** [comment]
const wheel1Geometry = generateConfig(
            CONFIGTYPE.LOADGEOMETRY,
            Object.assign(Object.values(resourceConfig["/model/wheel/wheel1.obj"].geometry)[0], {
                position: {
                    x: 3.3,
                    y: -4.5,
                    z: 6,
                },
                scale: {
                    x: 0.5,
                    y: 0.5,
                    z: 0.5,
                },
            })
        );
        const wheel1Material = generateConfig(CONFIGTYPE.MESHSTANDARDMATERIAL, {
            color: "rgb(25,24,24)",
            metalness: 1,
            roughness: 0,
            opacity: 0.8,
        });
        const wheel1Mesh = generateConfig(CONFIGTYPE.MESH, {
            geometry: wheel1Geometry.vid,
            material: wheel1Material.vid,
        });

        console.log(wheel1Mesh)
结果
![snipaste20240116_160247](https://github.com/vis-three/vis-three/assets/143592190/ae534a2e-a960-49af-923a-2756b271ea21)

**Comment by Shiotsukikaedesari** [comment]
配置本身是做了简化，通过rotation代理物体的旋转，如果要用quaternion可以这样做：
1、获取到真实物体，通过engine.getObjectBySymbol进行
2、直接通过rotation自己new一个临时的quaternion，new Quaternion().setFromEuler(new Euler(rotation.x, y, z))
3、如果本身业务中需要经常用到quaternion属性，可以自定义object配置模块然后替换使用。

**Comment by Shiotsukikaedesari** [comment]
第一种方法最简单：
```js
const configMesh = generateConfig('Mesh', {
    geometry: geometry.vid,
    material: material.vid
})

engine.applyConfig(configMesh)

const rawMesh = engine.getObjectBySymbol(configMesh.vid)
```

上面的rawMesh就是被代理的THREE.Mesh对象，其中就会有quaternion

只不过当你使用这种方法修改了THREE.Mesh对象的属性之后，需要同步相关配置到configMesh对象上，因为代理目前是单向的。
```js
rawMesh.quaternion.setFromAxisAngle( new THREE.Vector3( 0, 1, 0 ), Math.PI / 2 );

// .... other operate...

rawMesh.updateMatrix();

configMesh.rotation.x = rawMesh.rotation.x;
configMesh.rotation.y = rawMesh.rotation.y;
configMesh.rotation.z = rawMesh.rotation.z;
```

**Comment by Shiotsukikaedesari** [comment]
后面有问题不要再这个issue提问了，请新建issue。
