### ISSUE TITLE
Cannot install dependencies in stackblitz

### ISSUE THREAD

**Issue by pwlviolet** [vis-three/vis-three#22]
### 问题描述

I fork this Repositories and try to pnpm i dependencies in stackblitz,but it can't install dependencies. I am not familiar with PNPM.I hope these dependencies can be installed in stackblitz.what should i do?

### 问题或报错截图

![stackblit](https://github.com/vis-three/vis-three/assets/74035710/30e2a46b-af12-4b6a-a968-357c3c605f5d)
![stackblit2](https://github.com/vis-three/vis-three/assets/74035710/0b1dea98-a97a-46a4-a016-03068a38767a)

Progress: total 1112, downloaded 1103
 ERROR  Failed to fetch dependencies:
- fast-diff@1.2.0
- md5@2.3.0
- request-progress@3.0.0
- dayjs@1.10.7
- @babel/helper-module-transforms@7.20.11
- throttleit@1.0.0
- @algolia/autocomplete-shared@1.8.2
- @eslint/eslintrc@1.4.0
- schema-utils@3.1.1

HttpError: Failed to fetch dependencies:
- fast-diff@1.2.0
- md5@2.3.0
- request-progress@3.0.0
- dayjs@1.10.7
- @babel/helper-module-transforms@7.20.11
- throttleit@1.0.0
- @algolia/autocomplete-shared@1.8.2
- @eslint/eslintrc@1.4.0
- schema-utils@3.1.1
    at _0x13327e.fetchDependencies (https://w-corp.staticblitz.com/fetch.worker.22b9f6d5.js:1:262853)

### 运行环境

```bash
❯ node -v
v18.18.0
```

### 可调试环境

https://stackblitz.com/~/github.com/pwlviolet/vis-three

### 附加代码上下文

```ts
None
```

### 解决问题的回报选择

提供修复 pr 或者完善项目（解决任务issue，文档完善，代码优化，示例优化等等）。

**Comment by Shiotsukikaedesari** [comment]
screen shot show that these are http errors, some problem with your network environment. In PNPM or NPM , we can use .npmrc file to set up some configurations like http or https proxy. I found prxoy attribute in your .npmrc in project, this may be the reason for the http error.
