### ISSUE TITLE
启动 packages/examples 和packages/website时候报错

### ISSUE THREAD

**Issue by xiechangle** [vis-three/vis-three#40]
### 问题描述

```bash
是不是vis-three/packages/library/package.json少安装了"@vis-three/middleware" 库
```

### 问题或报错截图

![企业微信截图_20240812215255](https://github.com/user-attachments/assets/5db306fc-281d-44b9-8d09-744cf699ec4d)
![企业微信截图_20240812215335](https://github.com/user-attachments/assets/098bed00-4a5e-483d-8a27-6710649eb8ca)

### 运行环境

```bash
系统: windows@10
浏览器： chrome@131
脚手架： vite@2.9.15
node: 14.20.0
```

**Comment by Shiotsukikaedesari** [comment]
这个问题目前推测是依赖安装的问题，如果使用的是main分支，由于目前main分支正在进行大版本更新，部分依赖有所变更，所以推荐使用0.6分支进行，切换后重新安装依赖。
