### ISSUE TITLE
pnpm install 报错

### ISSUE THREAD

**Issue by chris118** [vis-three/vis-three#43]
### 问题描述

```bash
git clone https://github.com/vis-three/vis-three.git
cd vis-three
pnpm i

组合node 18 20 22, pnpm 8 9 10 都会有同样的错误
切换国内不同的npm源也一样
```

### 问题或报错截图

无
![微信截图_20241214104648](https://github.com/user-attachments/assets/0ec4aa05-d089-4778-8ee9-803fdd41e5f7)

### 运行环境

```bash
系统: windows@10
浏览器： chrome@131
脚手架： vite@2.9.15
node: 20.12.2
```

**Comment by Shiotsukikaedesari** [comment]
应该和这个是相同的问题：https://github.com/vis-three/vis-three/issues/22

**Comment by chris118** [comment]
![微信截图_20241215124351](https://github.com/user-attachments/assets/4016c1cb-8af0-49d2-9ec0-f78409538f8a)
删除.npmrc 里所有配置，还是报错

**Comment by Shiotsukikaedesari** [comment]
报错显示是网络的问题，如果删除代理后还出现类似问题，有可能存在的情况：
1、电脑网络本身无法访问相关的地址资源。——请检查本身的网络环境是否支持相关的资源访问。
2、使用pnpm进行依赖下载的请求本身无法访问相关的地址资源。——请检查pnpm服务或者npm服务本身是否支持相关地址资源的访问。
3、pnpm本身会存在pnpm-lock.yaml，如果切换了源之后，可能会存在一定的冲突，可以删除进行，但是在后期的资源同步与代码更新上会跟主分支产生冲突，不是十分建议。

**Comment by chris118** [comment]
![微信截图_20241216084738](https://github.com/user-attachments/assets/78e7e7b1-4a21-4a8d-8c7e-2ac301c63bb7)
1.资源可以访问
2. 删除pnpm-lock.yaml
还是同样的错误，而且换了一台电脑仍然同样错误

**Comment by Shiotsukikaedesari** [comment]
重新测试过了没有碰到相关的问题，可以提供一个可以复现问题的代码环境，比如：https://stackblitz.com

**Comment by Shiotsukikaedesari** [comment]
通过浏览器访问资源能够通过，不一定代表着npm，pnpm服务就可以，因为相关的梯子不一定就能够代理到npm,pnpm服务，所以.npmrc才会设置代理服务。

**Comment by chris118** [comment]
![微信截图_20241216123856](https://github.com/user-attachments/assets/ba1684d1-2396-4b6a-92bc-4f59a3085528)
已经找到问题了， 如果本地电脑有代理，要把pnpm的代理设置成一样。

**Comment by chris118** [comment]
![微信截图_20241216124906](https://github.com/user-attachments/assets/1e328dd5-cba5-44e0-9c51-ebef7e04fb90)
源代码根目录的 .npmrc文件里边默认设置了代理导致此问题
