### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by sheerhr** [vis-three/vis-three#8]
engine.play()编译报错
engine.render()方法未提供默认参数

**Comment by Shiotsukikaedesari** [comment]
编译报错不是框架的问题，是项目自己的问题。

**Comment by sheerhr** [comment]
> 编译报错不是框架的问题，是项目自己的问题。

他这边报的式engine上边没有属性play,defineEngine的返回值有play方法吗，不是用了RenderManagerPlugin才有的play方法吗

**Comment by Shiotsukikaedesari** [comment]
或者可以是用class extends模式，预构建自己的engine 类，详情可以参照预置引擎代码：https://github.com/vis-three/vis-three/blob/main/packages/engine/display/index.ts

**Comment by sheerhr** [comment]
好的，万分感谢

朱钒
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vis-three/vis-three"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月22日(星期三) 中午11:21
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [vis-three/vis-three] 编译报错 (Issue #8)





 
或者可以是用class extends模式，预构建自己的engine 类，详情可以参照预置引擎代码：https://github.com/vis-three/vis-three/blob/main/packages/engine/display/index.ts
